apiVersion: v1
kind: Secret
metadata:
  name: container-registry-secrets
  annotations:
    build.knative.dev/docker-0: ${container.registry.url}
type: kubernetes.io/basic-auth
stringData:
  username: ${container.registry.user}
  password: ${container.registry.password}