apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: quarkus-quickstart-knative
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              revision: "${git.source.revision}"
              url: "${git.source.repo.url}"
          steps:
            - args:
                - --context=/workspace/getting-started-knative
                - --dockerfile=/workspace/getting-started-knative/Dockerfile
                - --destination=${app.container.image}
              env:
                - name: DOCKER_CONFIG
                  value: /builder/home/.docker
              image: gcr.io/kaniko-project/executor
              name: docker-push
              volumeMounts:
                - mountPath: /builder/home/.m2
                  name: m2-cache
                - mountPath: /cache
                  name: kaniko-cache
              workingDir: /workspace/getting-started-knative
          timeout: 60m
          volumes:
            - name: m2-cache
              emptyDir: {}
            - name: kaniko-cache
              emptyDir: {}
      revisionTemplate:
        metadata:
          labels:
            app: getting-started-knative
        spec:
          container:
            image: ${app.container.image}